# Generated by Django 4.0.6 on 2023-03-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='end_date',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
