# Generated by Django 4.0.6 on 2023-03-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tasks_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='end_date',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
