# Generated by Django 4.0.6 on 2023-03-13 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tasks_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='todolist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist', to='api.list'),
        ),
    ]
