# Generated by Django 4.0.6 on 2023-03-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tasks_complete_alter_tasks_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
