# Generated by Django 4.0.6 on 2023-03-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_tasks_complete_tasks_komplete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='komplete',
            new_name='complete',
        ),
    ]
