# Generated by Django 4.0.6 on 2023-03-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_komplete_tasks_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='lastchecked',
            field=models.DateTimeField(null=True),
        ),
    ]
