# Generated by Django 4.0.6 on 2023-03-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tasks_lastchecked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='lastchecked',
        ),
        migrations.AddField(
            model_name='daily',
            name='lastchecked',
            field=models.DateTimeField(null=True),
        ),
    ]
