# Generated by Django 4.0.6 on 2023-03-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_tasks_lastchecked_daily_lastchecked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='lastchecked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
